description: "This research project develops training materials for reseachers wanting to learn to build project websites in GitHub with GitHub Pages."
title: "ISCB-AFRICA ASBCB CONFERENCE ON BIOINFORMATICS"
email: "azuza@mlw.mw"
kleb_image: "https://github.com/4youalways/portfolio/blob/gh-pages/images/zuza.webp"
poster: "https://github.com/4youalways/portfolio/blob/gh-pages/images/Africa2025_52_Zuza_poster.jpg"
