description: "This research project develops training materials for reseachers wanting to learn to build project websites in GitHub with GitHub Pages."
email: "azuza@mlw.mw"
kleb_image: "https://raw.githubusercontent.com/4youalways/portfolio/refs/heads/gh-pages/images/zuza.webp"
poster: "https://raw.githubusercontent.com/4youalways/portfolio/refs/heads/gh-pages/images/klebsiella_biology_poster_V5.webp"
